[package]
name = "ul-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"]}
serde_json = "1.0.132"
ssi-caips = "0.2.1"
thiserror = "2.0.3"
